In [18]:
import pandas as pd
import numpy as np

In [19]:
drug_interaction=pd.read_csv("drug_interaction_drugcomb.csv",low_memory=False)

In [20]:
drug_interaction.head()

,block_id,drug_row,drug_col,cell_line_name,conc_r_unit,conc_c_unit,css,synergy_zip,synergy_bliss,synergy_loewe,synergy_hsa,ic50_row,ic50_col,ri_row,ri_col,css_row,css_col,S
0,1,5-FU,ABT-888,A2058,uM,uM,30.869,3.865915,6.256584,-2.951386,5.536903,5.126836,3.267734,11.471,-0.441,22.545,39.193,19.839
1,2,5-FU,ABT-888,A2058,uM,uM,27.460,8.247403,12.333896,3.125927,11.614215,5.126836,3.267734,11.471,-0.441,24.135,30.785,16.430
2,3,5-FU,ABT-888,A2058,uM,uM,29.901,6.063440,11.660209,2.452239,10.940528,5.126836,3.267734,11.471,-0.441,25.561,34.241,18.871
3,4,5-FU,ABT-888,A2058,uM,uM,24.016,-4.280231,5.145209,-4.062761,4.425528,5.126836,3.267734,11.471,-0.441,16.661,31.371,12.986
4,5,5-FU,AZD1775,A2058,uM,uM,66.847,12.284698,15.765467,10.409407,18.656340,5.126836,0.266027,11.471,25.164,76.501,57.193,30.212

In [21]:
drug_interaction.shape

(1048575, 18)

In [22]:
drug_interaction.isnull().sum()

block_id               0
drug_row               0
drug_col          582542
cell_line_name         0
conc_r_unit            0
conc_c_unit       582542
css                    0
synergy_zip            0
synergy_bliss          0
synergy_loewe          0
synergy_hsa            0
ic50_row               0
ic50_col               0
ri_row                 0
ri_col                 0
css_row                0
css_col                0
S                      0
dtype: int64

In [23]:
drug_interaction.dropna(inplace=True)

In [24]:
drug_interaction.isnull().sum()

block_id          0
drug_row          0
drug_col          0
cell_line_name    0
conc_r_unit       0
conc_c_unit       0
css               0
synergy_zip       0
synergy_bliss     0
synergy_loewe     0
synergy_hsa       0
ic50_row          0
ic50_col          0
ri_row            0
ri_col            0
css_row           0
css_col           0
S                 0
dtype: int64

In [25]:
print("total number of drug involved",len(np.unique(np.concat([drug_interaction['drug_row'],drug_interaction['drug_row']]))))

total number of drug involved 4150

In [26]:
print("total number of cell line involved",len(drug_interaction['cell_line_name'].unique()))

total number of cell line involved 112

In [27]:
drug_feature=pd.read_csv("drug_feature.csv",index_col=0)

In [28]:
drug_feature.head()

,drug,0,1,2,3,4,5,6,7,8,...,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047
0,5-FU,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ABT-888,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AZD1775,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,BEZ-235,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,BORTEZOMIB,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
drug_feature.shape

(4051, 2049)

In [30]:
print("total number of drug",len(drug_feature['drug'].unique()))

total number of drug 4051

In [31]:
cell_line_feature=pd.read_csv("final_cell_line_feature.csv",index_col=0)

In [32]:
cell_line_feature.head()

,cell_line_name,ENSG00000000003,ENSG00000000005,ENSG00000000419,ENSG00000000457,ENSG00000000460,ENSG00000000938,ENSG00000000971,ENSG00000001036,ENSG00000001084,...,ENSG00000273238,ENSG00000273259,ENSG00000273269,ENSG00000273274,ENSG00000273291,ENSG00000273294,ENSG00000273313,ENSG00000273331,ENSG00000273345,ENSG00000273398
0,A2058,15.67,0.00,97.03,5.11,23.03,0.02,7.43,94.70,14.35,...,0.00,0.28,0.0,0.08,0.0,0.87,0.00,0.00,0.18,0.06
1,A2780,94.32,2.53,119.23,5.92,21.57,0.03,248.72,19.78,12.86,...,0.06,0.00,0.0,0.13,0.0,0.00,0.02,0.00,0.22,0.03
3,A427,19.18,0.00,95.22,2.73,11.14,0.01,0.13,45.33,10.43,...,0.00,0.00,0.0,0.16,0.0,0.13,0.04,0.02,0.06,0.05
20,NCI-H460,23.21,0.00,82.35,2.74,19.65,0.02,12.89,43.91,65.63,...,0.00,0.00,0.0,0.00,0.0,0.06,0.23,0.23,0.06,0.07
26,RKO,11.89,0.02,153.59,1.43,12.71,0.00,0.13,56.71,15.72,...,0.00,0.00,0.0,0.00,0.0,0.00,6.03,0.49,0.49,0.00

In [33]:
cell_line_feature.shape

(717, 19226)

In [34]:
print("total number of cell line involved",len(cell_line_feature['cell_line_name'].unique()))

total number of cell line involved 717

In [41]:
df_zip = drug_interaction.copy()
df_zip['label'] = (df_zip['synergy_zip'] > 0).astype(int)

df_bliss = drug_interaction.copy()
df_bliss['label'] = (df_bliss['synergy_bliss'] > 0).astype(int)

df_loewe = drug_interaction.copy()
df_loewe['label'] = (df_loewe['synergy_loewe'] > 0).astype(int)


df_hsa = drug_interaction.copy()
df_hsa['label'] = (df_hsa['synergy_hsa'] > 0).astype(int)

In [42]:
df_zip.head()

,block_id,drug_row,drug_col,cell_line_name,conc_r_unit,conc_c_unit,css,synergy_zip,synergy_bliss,synergy_loewe,synergy_hsa,ic50_row,ic50_col,ri_row,ri_col,css_row,css_col,S,label
0,1,5-FU,ABT-888,A2058,uM,uM,30.869,3.865915,6.256584,-2.951386,5.536903,5.126836,3.267734,11.471,-0.441,22.545,39.193,19.839,1
1,2,5-FU,ABT-888,A2058,uM,uM,27.460,8.247403,12.333896,3.125927,11.614215,5.126836,3.267734,11.471,-0.441,24.135,30.785,16.430,1
2,3,5-FU,ABT-888,A2058,uM,uM,29.901,6.063440,11.660209,2.452239,10.940528,5.126836,3.267734,11.471,-0.441,25.561,34.241,18.871,1
3,4,5-FU,ABT-888,A2058,uM,uM,24.016,-4.280231,5.145209,-4.062761,4.425528,5.126836,3.267734,11.471,-0.441,16.661,31.371,12.986,0
4,5,5-FU,AZD1775,A2058,uM,uM,66.847,12.284698,15.765467,10.409407,18.656340,5.126836,0.266027,11.471,25.164,76.501,57.193,30.212,1

In [43]:
df_zip.label.value_counts()

label
0    258510
1    207523
Name: count, dtype: int64

In [44]:
df_bliss.label.value_counts()

label
1    236979
0    229054
Name: count, dtype: int64

In [45]:
df_loewe.label.value_counts()

label
0    335837
1    130196
Name: count, dtype: int64

In [48]:
df_hsa.label.value_counts()

label
1    238972
0    227061
Name: count, dtype: int64